ecommerce/cartapp/urls.py
from django.urls import path
from . import views

app_name = 'cart'
app_name = 'cartapp'
urlpatterns = [
    path('add/<int:product_id>/', views.addcart, name='add_cart'),
    path('remove/<int:product_id>/', views.removecart, name='remove_cart'),
    path('delete/<int:product_id>/', views.deletecart, name='delete_cart'),
    path('', views.cart_detail, name='cart_detail'),
]

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopapp.urls')),
    path('searchapp/', include('searchapp.urls')),
    path('cartapp/', include('cartapp.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/searchapp/urls.py
from django.urls import path
from . import views

app_name='searchapp'
urlpatterns=[
    path('',views.SearchResult, name='SearchResult'),
]

ecommerce/shopapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views
app_name='shopapp'
urlpatterns = [
    path('', views.AllProductCat, name='AllProductCat'),
    path('<slug:c_slug>/',views.AllProductCat, name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.pdetail, name='productCatdetail'),

]

ecommerce/cartapp/models.py
from django.db import models
from shopapp.models import Product


# Create your views here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'cart'
        ordering = ['date_added']

        def __str__(self):
            return '{}'.format(self.cart_id)


class Cartitem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'cartitem'

    def subtotal(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce/shopapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    objects = None
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)


def __str__(self):
    return '{}'.format(self.name)






class Product(models.Model):
    objects = None
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def get_url(self):
        return reverse('shopapp:productCatdetail', args=[self.category.slug, self.slug])


class Meta:
    ordering = ('name',)
    verbose_name = 'product'
    verbose_name_plural = 'products'

ecommerce/cartapp/views.py
from django.http import HttpResponseBadRequest, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from shopapp.models import Product
from .models import Cart, Cartitem
from django.core.exceptions import ObjectDoesNotExist


def cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def addcart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=cart_id(request))
        cart.save()
    try:
        cart_item = Cartitem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except Cartitem.DoesNotExist:
        cart_item = Cartitem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cartapp:cart_detail')


def removecart(request, product_id):
    cart = Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = Cartitem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect("cartapp:cart_detail")

def deletecart(request, product_id):
    try:
        product = Product.objects.get(id=product_id)
        cart = Cart.objects.get(cart_id=cart_id(request))
        cart_item = Cartitem.objects.get(product=product, cart=cart)

        cart_item.delete()  # Delete the cart item

        return redirect('cartapp:cart_detail')
    except (Product.DoesNotExist, Cart.DoesNotExist, Cartitem.DoesNotExist):
        return redirect('cartapp:cart_detail')
def cart_detail(request, total=0, counter=0, cart_item=None):
    cart_items=[]
    try:
        cart = Cart.objects.get(cart_id=cart_id(request))
        cart_items = Cartitem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))

ecommerce/searchapp/views.py
from django.shortcuts import render
from shopapp.models import Product
from django.db.models import Q
# Create your views here.

def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query= request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html', {'query':query,'products':products})

ecommerce/shopapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


def AllProductCat(request, c_slug=None):
    c_page = None
    product_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.filter(category=c_page, available=True).order_by('name')
    else:
        products_list = Product.objects.filter(available=True).order_by('name')

    paginator = Paginator(products_list, 6)

    page = request.GET.get('page', 1)
    try:
        page = int(page)
    except ValueError:
        page = 1

    try:
        products = paginator.page(page)
    except(EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, "category.html", {'category': c_page, 'products': products})


def pdetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product':product})

ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/6962d425d9.js" crossorigin="anonymous"></script>    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>


</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
       This is the Cart page. procced to review your items and place the order
{% endblock %}
{% block title %}
    Cart - P Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shoping Cart
        </h1>
        <br>
        <p class="text-center">
            Please click <a href="{% url 'shopapp:AllProductCat' %}"> Here</a> to continue shopping
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping cart
        </h1>
        <br>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                       Your Items:
                    </th>

                </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="image" class="float-left rounded custom_image" width="250" height="300"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU:{{cart_item.product.id}}
                        <br>
                        Price:{{cart_item.product.price}}
                        <br>
                        Qty:{{cart_item.quantity}} x {{cart_item}}
                    </td>
                    <td>
                        $ {{cart_item.subtotal}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cartapp:add_cart' cart_item.product.id %}" class="custom_a" > <i class="fa-solid fa-plus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cartapp:remove_cart' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-minus"></i></a>
                        &nbsp;<a href="{% url 'cartapp:delete_cart' cart_item.product.id %}" class="custom_icon"> <i class="fa-solid fa-trash"></i></a>
                    </td>
                    {% else %}
                    <td>
                        &nbsp;<a href="" class="custom_a"> <i class="fa-light fa-minus custom_icon"></i></a>
                        &nbsp;<a href="" class="custom_icon"> <i class="fa-light fa-trash custom_icon"></i></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_head">
            <tbody>
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            <tr>
                <td>
                    Please review your shopping cart items before proceeding with the payment.
                </td>
            </tr>
                <td class="text-left">
                    Your total is :<strong>{{ total }}</strong>
                </td>
            </tbody>
            </thead>
        </table>
    <div class="mx-auto">
    <a href="{%url 'shopapp:AllProductCat' %}" class="btn btn-secondary btn-block my_custom_button">Proceed</a>
    </div>
    </div>
</div>
{% endif %}
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to P Cart store where you can buy many things
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}} - P Cart
    {% else %}
        See the New Collections - P Cart
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
    <div>
        <div class="row-my_row_class">
            <div class="mx_auto">
            <p><a href="{% url 'shopapp:AllProductCat' %}">Our product collections</a> </p>
        </div>
            </div>
    </div>
    {% endif %}
<div class="mx_auto">
    {% if category %}
    <img  class="my_image" src="{{category.image.url}}" alt="{{category.name}}" >
</div>
<br>
<div>
    <h1 class="text-center my_title" >{{category.name}}</h1>
    <p>{{category.description}}</p>
</div>
    {% else %}
<div>
<img src="{% static 'img/PCART.png' %}" alt="our Products" width="1300" height="500">
</div>
<br>
<div>
    <h1 class="text-center my_title">Our products</h1>
    <p class="text-justify">Compared to other sites we are providing a huge offer to our customers</p>
</div>
    {% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img  class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"  height="450"></a>
            <div class="card-body">
                <p>{{product.name}}</p>
                <p>{{product.price}}</p>
            </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>

{% endblock %}

ecommerce/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; P cart pvt ltd. All Rights Reserved </p>
</div>

ecommerce/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'shopapp:AllProductCat' %}"> <img src="{% static 'img/P.png' %}" alt="logo_image" width="120" height="150"></a>

  </center>
</header>

ecommerce/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shopapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shopapp:AllProductCat' %}">All Products</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'cartapp:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
        </li>

      </ul>
      <form class="d-flex" role="search" action="{% url 'searchapp:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i>Search</button>
      </form>
    </div>
  </div>
</nav>

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ product.description|truncatewords:180 }}
{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }}
    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
  <div class="mx_auto">
    <p><a href="{% url 'shopapp:AllProductCat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{ product.category }}</a> | {{ product.name }}</p>
  </div>
  <div class="container">
<br>
<div class="row ">
  <div class="col-md-12 col-sm-12 col-md-12 col-lg-12 text-center">
    <div style="min-width:18rem">
      <img src="{{ product.image.url }}" alt="{{ product.name }}" width="250" height="300">
    </div>
  </div>

    <div class=" col-12 col-sm-12 col-md-12 col-lg-6">
      <div>
      <h1 class="my_prod_title">{{product.name}}</h1>
      <p>{{ product.price }}</p>
      <p class="my_title">Product Description</p>
      <p  class="text-justify my_prod_text" >{{product.description}}</p>
      {% if product.stock <= 0 %}
        <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
      {% else %}
        <a class="btn btn-secondary" href="{% url 'cartapp:add_cart' product.id %}">Add to cart</a>
      {% endif %}
    </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        We have veriety of products
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
        <p class="text-center my_searcg-text">You have searched for :<b>"{{query}}"</b></p>
</div>
<div class="container">
 <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.grt_url}}"><img  class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" width="500" height="250"></a>
            <div class="card-body">
                <p>{{product.name}}</p>
                <p>{{product.price}}</p>
            </div>
            </div>
        </div>
        {% empty %}
         <div class="row mx-auto">
                 <p class="text-center my_search_text">0 results found</p>
         </div>
         {% endfor %}
    </div>
</div>
{% endblock %}